version: "3.3"

services:

    mongo:
        image: andresvidal/rpi3-mongodb3 # cannot use official mongo image! (no arm/v7 image provided -> need to create my own)
        container_name: pers-wiz-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db

    node:
        build:
          context: ./src
          dockerfile: live.Dockerfile
        container_name: pers-wiz-node
        restart: always
        depends_on:
            - mongo
        ports:
            - "2002:2002"
            - "2005:2005"
            - "2006:2006"


volumes:
  mongo:
