version: "3.3"

services:

    mongo:
        build: ./mongo-pi # cannot use official mongo image! (not compatible with rasp pi)
        container_name: pers-wiz-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db

    node:
        build:
          context: ./src
          dockerfile: live.Dockerfile
        container_name: pers-wiz-node
        restart: always
        depends_on:
            - mongo
        ports:
            - "2005:2005"
            - "2006:2006"


volumes:
  mongo:
