version: "3.3"

services:

    node:
        build: src
        container_name: pers-wiz-node
        restart: always
        ports:
            - "80:2005"
            - "443:2006"

    mongo:
        image: mongo:bionic
        container_name: pers-wiz-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db
