version: "3.3"

services:

    mongo:
        image: mongo:3.4 # stay on the same major version as pi mongo docker
        container_name: pers-wiz-mongo
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db

    node:
        build: ./src
        container_name: pers-wiz-node
        depends_on:
            - mongo
        ports:
            - "2002:2002"
            - "80:2005"
            - "443:2006"
        volumes:
            - ./src:/opt/personalWizard