version: "3.3"

services:

    mongo:
        image: mongo:3.4 # stay on the same major version as pi mongo docker
        container_name: pers-wiz-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db

    node:
        build: ./src
        container_name: pers-wiz-node
        restart: always
        depends_on:
            - mongo
        ports:
            - "80:2005"
            - "443:2006"
        volumes:
            - ./src:/opt/personalWizard